d

diff --git a/Automation/jenkinsfileDeploy b/Automation/jenkinsfileDeploy
--- a/Automation/jenkinsfileDeploy
+++ b/Automation/jenkinsfileDeploy
@@ -8,7 +8,7 @@ pipeline{
         CODE_DIR='movie-land'
         TAG = 'v1.${BUILD_NUMBER}'
         ACCOUNT_NAME= 'yit1977ltld/apiproject'
-        IMAGE_NAME = '${ACCOUNT_NAME}:latest'
+        IMAGE_NAME = "${ACCOUNT_NAME}:latest"
         REGISTRY= 'hub.docker.com'
         DOCKERHUB_CREDENIALS = credentials('DockerCred')
         SHARED_WORKSPACE = '/var/jenkins_home/workspace/Deploy Enviroment'
@@ -56,58 +56,107 @@ pipeline{
             }
             
         }
-        stage("SSH Connection and Install App") {
+        stage('Update and Upgrade System') {
             steps {
-                script {                    
-                    sshagent(credentials : ['devopsSSH']) {                        
-                    script {
-                        // Step 1: Update and Upgrade System
-                        sh """
-                            ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} 'sudo apt update && sudo apt upgrade -y'
-                        """
-                        // Step 2: Install Docker if not running
-                        sh """
-                            ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} '
-                            if ! command -v docker &> /dev/null; then
-                                sudo snap install docker &&
-                                sudo systemctl start docker
-                            else
-                                echo "Docker is already installed and running."
-                            fi'
-                        """
-                        // Step 3: Install Dependencies
-                        sh """
-                            ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} 'sudo apt-get install -qqy apt-transport-https ca-certificates curl gnupg2 software-properties-common wget sudo git'
-                        """
-                        // Step 4: Try to Remove Old Container
-                        sh """
-                            ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} '
-                            if sudo docker ps -a --format "{{.Names}}" | grep -Eq "^${CONTAINER_NAME}\$"; then
-                                sudo docker rm -f ${CONTAINER_NAME}
-                            else
-                                echo "Container ${CONTAINER_NAME} does not exist."
-                            fi'
-                        """
-                        // Step 5: Run Docker Container
-                        sh """
-                            ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} 'sudo docker run -d --name ${CONTAINER_NAME} -p ${EXTERNAL_APP_PORT}:${INTERNAL_APP_PORT} ${IMAGE_NAME}'
-                        """
-                    }
-                    }
+                sshagent(credentials: [CREDENTIALS_ID]) {
+                    sh """
+                        ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} 'sudo apt update && sudo apt upgrade -y'
+                    """
                 }
             }
             post {
                 success {
-                    echo "SSH connection successfully established and running api project"
+                    echo "Update and Upgrade successfully"
                 }
                 failure {
-                    echo "SSH connection failed"
+                    echo "Update and Upgrade failed"
+                }
+            }            
+        }
+        stage('Install Docker if not running') {
+            steps {
+                sshagent(credentials: [CREDENTIALS_ID]) {
+                    sh """
+                        ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} '
+                        if ! command -v docker &> /dev/null; then
+                            sudo snap install docker &&
+                            sudo systemctl start docker
+                        else
+                            echo "Docker is already installed and running."
+                        fi'
+                    """
                 }
             }
+            post {
+                success {
+                    echo "install Docker successfully"
+                }
+                failure {
+                    echo "install Docker failed"
+                }
+            } 
+            
         }
+        stage('Install Dependencies') {
+            steps {
+                sshagent(credentials: [CREDENTIALS_ID]) {
+                    sh """
+                        ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} 'sudo apt-get install -qqy apt-transport-https ca-certificates curl gnupg2 software-properties-common wget sudo git'
+                    """
+                }
+            }
+            post {
+                success {
+                    echo "Install Dependencies successfully"
+                }
+                failure {
+                    echo "Install Dependencies failed"
+                }
+            }             
+        }
+        stage('Remove Docker Container if exists') {
+            steps {
+                sshagent(credentials: [CREDENTIALS_ID]) {
+                    sh """
+                        ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} '
+                        if sudo docker ps -a --format "{{.Names}}" | grep -Eq "^${CONTAINER_NAME}\$"; then
+                            sudo docker rm -f ${CONTAINER_NAME}
+                        else
+                            echo "Container ${CONTAINER_NAME} does not exist."
+                        fi'
+                    """
+                }
+            }
+            post {
+                success {
+                    echo "Remove Docker Container if exists successfully"
+                }
+                failure {
+                    echo "Remove Docker Container if exists failed"
+                }
+            }  
+        }
+        stage('Run Docker Container') {
+            steps {
+                sshagent(credentials: [CREDENTIALS_ID]) {
+                    sh """
+                        ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} 'sudo docker run -d --name ${CONTAINER_NAME} -p ${EXTERNAL_APP_PORT}:${INTERNAL_APP_PORT} ${IMAGE_NAME}'
+                    """
+                }
+            }
+            post {
+                success {
+                    echo "Run New Docker Container successfully"
+                }
+                failure {
+                    echo "Run New Docker Container failed"
+                }
+            }              
+        }
+
         
     }
-   post{
+    post{
         always{
             echo "========pipeline Always ========"
         }
